// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SyncfusionASPNETCoreApplication2
{
    public partial class AArtProductClassification
    {
        public int ArtProductClassificationCode { get; set; }
        public string ArtProductClassificationDesc { get; set; }
    }
}